# Generated by Django 4.2.11 on 2025-11-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='stress_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
