# Generated by Django 4.2.11 on 2025-11-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0002_visit_stress_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_data',
        ),
    ]
