# Generated by Django 4.2.11 on 2025-11-08 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0003_remove_visit_visit_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_size', models.FloatField(help_text='Interwał czasowy między kolejnymi punktami pomiarowymi (w sekundach)')),
                ('total_duration_seconds', models.IntegerField(help_text='Całkowity czas trwania sesji (w sekundach)')),
                ('baseline_percentage', models.FloatField(help_text='Procent czasu przypisany do stanu Baseline (0.0-100.0)')),
                ('stress_percentage', models.FloatField(help_text='Procent czasu przypisany do stanu Stress (0.0-100.0)')),
                ('amusement_percentage', models.FloatField(help_text='Procent czasu przypisany do stanu Amusement (0.0-100.0)')),
                ('meditation_percentage', models.FloatField(help_text='Procent czasu przypisany do stanu Meditation (0.0-100.0)')),
                ('timeline_data', models.JSONField(blank=True, help_text='Lista punktów czasowych tworzących oś czasu sesji', null=True)),
                ('ai_summary_story', models.TextField(blank=True, help_text='Historia wygenerowana przez model AI podsumowująca sesję', null=True)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patient_management.visit')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
