# Generated by Django 4.2.11 on 2025-11-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0004_add_session_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='step_size',
            field=models.FloatField(blank=True, help_text='Interwał czasowy między kolejnymi punktami pomiarowymi (w sekundach)', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='total_duration_seconds',
            field=models.IntegerField(blank=True, help_text='Całkowity czas trwania sesji (w sekundach)', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='baseline_percentage',
            field=models.FloatField(blank=True, help_text='Procent czasu przypisany do stanu Baseline (0.0-100.0)', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='stress_percentage',
            field=models.FloatField(blank=True, help_text='Procent czasu przypisany do stanu Stress (0.0-100.0)', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='amusement_percentage',
            field=models.FloatField(blank=True, help_text='Procent czasu przypisany do stanu Amusement (0.0-100.0)', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='meditation_percentage',
            field=models.FloatField(blank=True, help_text='Procent czasu przypisany do stanu Meditation (0.0-100.0)', null=True),
        ),
    ]
