# Generated by Django 4.2.11 on 2025-11-08 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_default_user(apps, schema_editor):
    """Ustawia domyślnego użytkownika dla istniejących sesji"""
    Session = apps.get_model('patient_management', 'Session')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    
    # Jeśli są sesje bez użytkownika, przypisz pierwszego użytkownika lub superusera
    if Session.objects.filter(user__isnull=True).exists():
        default_user = User.objects.filter(is_superuser=True).first() or User.objects.first()
        if default_user:
            Session.objects.filter(user__isnull=True).update(user=default_user)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_management', '0005_make_session_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_default_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
