# Generated by Django 4.2.11 on 2025-11-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0008_remove_session_long_term_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='ai_summary_story',
            field=models.TextField(blank=True, help_text='Historia wygenerowana przez model AI podsumowująca sesję', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='amusement_percentage',
            field=models.FloatField(blank=True, help_text='Procent czasu przypisany do stanu Amusement (0.0-100.0)', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='baseline_percentage',
            field=models.FloatField(blank=True, help_text='Procent czasu przypisany do stanu Baseline (0.0-100.0)', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='meditation_percentage',
            field=models.FloatField(blank=True, help_text='Procent czasu przypisany do stanu Meditation (0.0-100.0)', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='step_size',
            field=models.FloatField(blank=True, help_text='Interwał czasowy między kolejnymi punktami pomiarowymi (w sekundach)', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='stress_percentage',
            field=models.FloatField(blank=True, help_text='Procent czasu przypisany do stanu Stress (0.0-100.0)', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='timeline_data',
            field=models.JSONField(blank=True, help_text='Lista punktów czasowych tworzących oś czasu sesji', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='total_duration_seconds',
            field=models.IntegerField(blank=True, help_text='Całkowity czas trwania sesji (w sekundach)', null=True),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
